### ISSUE TITLE
Problem With Instalation on Laravel 10

### ISSUE THREAD

**Issue by frizcool** [Keysaw/laravel-filament-maintenance#4]
### What happened?

I can't Install this pakage

### How to reproduce the bug

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - brickx/laravel-filament-maintenance[dev-main, 1.0.0, ..., 1.0.1] require illuminate/contracts ^10.11 -> found illuminate/contracts[v10.11.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires brickx/laravel-filament-maintenance * -> satisfiable by brickx/laravel-filament-maintenance[dev-main, 1.0.0, 1.0.1, 9999999-dev].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require brickx/laravel-filament-maintenance:*" to figure out if any version is installable, or "composer require brickx/laravel-filament-maintenance:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Package Version

1.0.1

### PHP Version

8.2.4

### Laravel Version

10.7.1

### Which operating systems does with happen with?

Windows

**Comment by Keysaw** [comment]
Hi there,

Can you share with me your composer.json, so I can pinpoint the issue?

Seems to me like a conflict with one of your dependencies. I will try to reproduce the issue on my end.

Thank you.

**Comment by mohamedary** [comment]
@Keysaw Hey I just ran into the same problem. Here goes:
<img width="999" alt="image" src="https://github.com/Keysaw/laravel-filament-maintenance/assets/17085444/1b2c6917-0b8e-4bb4-9481-6081749575da">

**Comment by Keysaw** [comment]
Hi @crayon1337,

Do you mind sharing your composer.json as well?

I need to replicate the issue on my end in order to release a proper fix.

Thank you.

**Comment by mohamedary** [comment]
Hi @Keysaw. 
There it is,
```JSON
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.2",
        "alperenersoy/filament-export": "^0.2.9",
        "archilex/filament-toggle-icon-column": "^1.0",
        "awcodes/overlook": "^1.0",
        "bezhansalleh/filament-shield": "^2.4",
        "creagia/filament-code-field": "^1.0",
        "filament/filament": "^2.0",
        "filament/spatie-laravel-media-library-plugin": "^2.0",
        "filament/spatie-laravel-settings-plugin": "^2.0",
        "filament/spatie-laravel-translatable-plugin": "^2.0",
        "flowframe/laravel-trend": "^0.1.5",
        "guava/filament-icon-picker": "^1.3",
        "guzzlehttp/guzzle": "^7.2",
        "konnco/filament-import": "^1.5",
        "laravel/framework": "^10.8",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "mcamara/laravel-localization": "^1.8",
        "owenvoke/blade-fontawesome": "^2.2",
        "solution-forest/filament-tree": "^1.0",
        "spatie/laravel-sitemap": "^6.3",
        "statikbe/laravel-filament-chained-translation-manager": "^1.1",
        "yepsua/filament-rating-field": "^0.1.1"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.8",
        "doctrine/dbal": "^3.6",
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "nunomaduro/larastan": "^2.0",
        "pestphp/pest": "^2.5",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0",
        "squizlabs/php_codesniffer": "3.*"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force",
            "@php artisan filament:upgrade"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

**Comment by Keysaw** [comment]
I wasn't able to replicate the issue in a fresh Laravel installation using your `composer.json`. Are all of your packages up-to-date?

However, I think the default version of `illuminate/contracts` generated by `spatie/package-skeleton-laravel` might be too restrictive, so I updated the `composer.json` of this package in the latest release.

Could you try installing the version [1.1.1](https://github.com/Keysaw/laravel-filament-maintenance/releases/tag/1.1.1), and tell me if the error still occurs?

**Comment by mohamedary** [comment]
> I wasn't able to replicate the issue in a fresh Laravel installation using your `composer.json`. Are all of your packages up-to-date?
> 
> However, I think the default version of `illuminate/contracts` generated by `spatie/package-skeleton-laravel` might be too restrictive, so I updated the `composer.json` of this package in the latest release.
> 
> Could you try installing the version [1.1.1](https://github.com/Keysaw/laravel-filament-maintenance/releases/tag/1.1.1), and tell me if the error still occurs?

Once I am able to I will try again and let you know.

**Comment by mohamedary** [comment]
Works perfectly fine, thank you @Keysaw :)

**Comment by Keysaw** [comment]
> Works perfectly fine, thank you @Keysaw :)

Glad to hear it! I'll close the issue then.
