### ISSUE TITLE
[Bug]: Documentation

### ISSUE THREAD

**Issue by HeartlandTechie** [Keysaw/laravel-filament-maintenance#7]
### What happened?

I did this on a fresh install and got a few errors.  The actual information for the fix on redirect might be better with the complete included files needed: 

`<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\MaintenanceModeBypassCookie;
use Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance as Middleware;
use Illuminate\Http\RedirectResponse;

class PreventRequestsDuringMaintenance extends Middleware
{
    /**
     * The URIs that should be reachable while maintenance mode is enabled.
     *
     * @var array<int, string>
     */
    protected $except = [
        //
    ];

    protected function bypassResponse(string $secret) : RedirectResponse
    {
        return redirect('admin')->withCookie(
            MaintenanceModeBypassCookie::create($secret)
        );
    }
}
`

### How to reproduce the bug

If you leave these out:  

```
use Illuminate\Foundation\Http\MaintenanceModeBypassCookie;
use Illuminate\Http\RedirectResponse;
```

It will break

### Package Version

latest

### PHP Version

8.1

### Laravel Version

10

**Comment by Keysaw** [comment]
Thank you! I didn't think of that since my IDE always takes care of importing, but I guess it's better to be exhaustive.

I'll only add the necessary classes to import, since everything else in the file is just the default Laravel class.

**Comment by HeartlandTechie** [comment]
Thank you!  Yes, I figured that might be the case as PhpStorm does this but if I'm doing something with VisualStudio or just a quick edit I would totally miss this.  I've been in Laravel for ten years and I still don't know if I understand enough to make it all work.
